### PR TITLE
fix: ignore adding scope hash when styles are not scoped

### LINKED ISSUE #32: Ignore adding scope hash when styles are not scoped
```vue
<AbellComponent>
<template>
  <!-- This code does not need to be scoped -->
  <div></div>
</template>
</AbellComponent>
```

```vue
<AbellComponent>
<template>
  <!-- This code does not need to be scoped -->
  <div></div>
</template>
<style global>
  /* global styles */
</style> 
</AbellComponent>
```

**Problem:**
In both of the above cases, CSS is not needed to be scoped. Above components will add `abell-data-<hash>` attribute to all html elements inside template.

And thus, it outputs:
```html
<div data-abell-kGoBAj></div>
```

`data-abell-<hash>` is required to scope CSS. But since in above examples, styles are not scoped, we can ignore adding hash to HTML elements.

**Expected:**
Component with this code is not required to be scoped so does not need those `abell-data` attributes. So they are expected to output.
```html
<div></div>
```

This is the function that adds those hashes to HTML output https://github.com/abelljs/abell-renderer/blob/main/src/parsers/component-parser.js#L158

We have to ignore calling this function if-
- `<style>` tag exists and has `global` attribute
- `<style>` tag does not exist

This is a good-first-issue so feel free to ask any additional questions in comments below

### PR DESCRIPTION
**Pull request by judicaelandria**
Fixes #32

### CODE REVIEW

File: src/parsers/component-parser.js [hunk 1]
```diff
@@ -155,6 +155,10 @@ function parseComponent(
     template = templateTag[1];
   }
   if (options && !options.skipHTMLHash) {
+    // ignore adding scope hash
+    if (styleMatches || !styleMatches) {
+      return;
+    }
     template = prefixHtmlTags(template, componentHash);
   }
```
Comment (saurabhdaware) [inline src/parsers/component-parser.js:163]: `styleMatches` variable will be undefined here since it is defined below. so we will have to move this part after defination of styleMatches.

File: src/parsers/component-parser.js [hunk 2]
```diff
@@ -155,6 +155,10 @@ function parseComponent(
     template = templateTag[1];
   }
   if (options && !options.skipHTMLHash) {
+    // ignore adding scope hash
+    if (styleMatches || !styleMatches) {
+      return;
+    }
     template = prefixHtmlTags(template, componentHash);
```
Comment (saurabhdaware) [inline src/parsers/component-parser.js:162]: styleMatches is an array of all the `<style>` tags. so when there are no style tags, it will be an empty array which we can check by checking if the length is zero. `styleMatches.length <= 0`

> - <style> tag does not exist
This will solve the second case as mentioned.


To fix the first case,
> - `<style>` tag exists and has global attribute

We have to loop through styleMatches array and check if all of the style tags have `global` attribute in them.

We can do that with `.every` method of JavaScript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every

So maybe we can do something like:

```suggestion
  const isStyleGlobal = styleMatches.length <= 0 || styleMatches.every(styleMatch => styleMatch.attributes.global === true))
  if ((options && !options.skipHTMLHash) || isStyleGlobal) {
    // ignore adding scope hash
    template = prefixHtmlTags(template, componentHash);
```

**Review by saurabhdaware — CHANGES_REQUESTED** [review]
Hi @judicaelandria I have suggested some changes below. I haven't checked if it works so you will have to check by changing and running any of the example.

**Comment by saurabhdaware** [comment]
You can test if your code is working or not by following the next steps-
- Run `npm run example examples/with-component` from project root
- In `examples/with-component/out.html`, check if the `<footer>` tag has an attribute called `data-abell-<hash>`. If it has attribute then something is wrong, if it does not have attribute then the changes you made worked.
- Now go to `examples/with-component/components/Footer.abell` and remove the `<style></style>` tag completely. Again check if it has `data-abell` attribute. If it does not have attribute, then it worked!

Our aim is to remove that `data-abell` attribute from elements when the style tag has `global` attribute or style tag does not exist.

**Comment by judicaelandria** [comment]
> You can test if your code is working or not by following the next steps-
> 
> * Run `npm run example examples/with-component` from project root
> * In `examples/with-component/out.html`, check if the `<footer>` tag has an attribute called `data-abell-<hash>`. If it has attribute then something is wrong, if it does not have attribute then the changes you made worked.
> * Now go to `examples/with-component/components/Footer.abell` and remove the `<style></style>` tag completely. Again check if it has `data-abell` attribute. If it does not have attribute, then it worked!
> 
> Our aim is to remove that `data-abell` attribute from elements when the style tag has `global` attribute or style tag does not exist.

we have something wrong here

**Comment by judicaelandria** [comment]
with every method because, like he's returning 3 value
false, false, and true, because we get 3 array

**Comment by saurabhdaware** [comment]
Yes, that is expected. It is because there are 3 components in with-examples. You can just see the output of `Footer.abell`

**Comment by judicaelandria** [comment]
I tried, he still getting the 3 result not only for footer
sdfsldfs

**Comment by saurabhdaware** [comment]
There's no issue in having 3 logs. That is how it is suppose to be.

**Comment by saurabhdaware** [comment]
I think the current code will work we just need to move it after defination of styleMatches

**Comment by judicaelandria** [comment]
it's already after the definition of styleMatches, I can't verify it right now because I don't have my pc with me

**Comment by saurabhdaware** [comment]
No problem! It's actually before defination in the commit. https://github.com/abelljs/abell-renderer/pull/34/files#diff-439461f7a42fba2d24f46f3a0ca6719fa65907e138d642929ef971960c3454cbR176

Just putting our code after this line is suppose to work.

**Comment by judicaelandria** [comment]
I didn't push my change, but here on my pc it's after the definition of styleMatches but it doesn't work

**Comment by saurabhdaware** [comment]
Oh, Are you sure the code you have locally is exactly the same as the one you've pushed except it being below defination? the code in screenshot that you've commented seems a little wrong.

**Comment by judicaelandria** [comment]
you can review now, I just pushed it

File: src/parsers/component-parser.js [hunk 3]
```diff
@@ -181,6 +178,27 @@ function parseComponent(
...
+  const isFooter = styleMatches.every((styleMatch) => isGlobal(styleMatch));
+
+  if (
+    (options && !options.skipHTMLHash) ||
+    styleMatches.length > 0 ||
+    isFooter
+  ) {
+    // ignore adding scope hash
+    template = prefixHtmlTags(template, componentHash);
+  }
```
Comment (saurabhdaware) [inline src/parsers/component-parser.js]:
```suggestion
  const shouldScopeTemplate = styleMatches.length <= 0 || styleMatches.every((styleMatch) => styleMatch.attributes.global === true);

  if (
    (options && !options.skipHTMLHash) ||
    styleMatches.length > 0 ||
    shouldScopeTemplate
  ) {
    // ignore adding scope hash
    template = prefixHtmlTags(template, componentHash);
  }
```

This code looks right to me. It checks if there are no style tags and checks if style tags exist then every style tag has global attribute

**Review by saurabhdaware — CHANGES_REQUESTED** [review]

**Comment by saurabhdaware** [comment]
Oh yeah seems right! I'll check locally.

**Comment by judicaelandria** [comment]
notify me after you test it

**Comment by saurabhdaware** [comment]
Woops fixed! The condition was suppose to be `if (options && !options.skipHTMLHash && !isStyleGlobal) {`

**Review by saurabhdaware — APPROVED** [review]
Looks great! Thank you so much @judicaelandria :tada:

**Comment by judicaelandria** [comment]
> Looks great! Thank you so much @judicaelandria 🎉

My pleasure, thank you
